import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { chromium } from '@playwright/test'

const base = process.env.ATLAS_URL || 'http://127.0.0.1:3333'
const output = process.env.ATLAS_QA_DIR || 'work/qa'
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-unsafe-webgpu', '--enable-unsafe-swiftshader'] })
const context = await browser.newContext({ locale: 'en-US', viewport: { width: 1440, height: 1000 }, acceptDownloads: true })
const page = await context.newPage()
const errors = []
page.on('pageerror', error => errors.push(error.message))
const ready = async p => {
  await p.getByText('LIVE VIEW', { exact: true }).waitFor({ timeout: 120_000 })
  await p.locator('.loader').waitFor({ state: 'hidden' })
  await p.locator('canvas').waitFor()
}
const noOverflow = async p => assert(await p.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'horizontal overflow')
try {
await page.goto(base)
await ready(page)
await noOverflow(page)
await page.screenshot({ path: `${output}/desktop.png`, fullPage: true })
await page.getByRole('button', { name: 'Pause animation', exact: true }).click()
await page.waitForTimeout(500)
const paused = await page.locator('canvas').screenshot()
await page.waitForTimeout(400)
assert(paused.equals(await page.locator('canvas').screenshot()), 'Pause must stop animation')
await page.getByRole('button', { name: 'Play animation', exact: true }).click()
await page.waitForTimeout(300)
assert(!paused.equals(await page.locator('canvas').screenshot()), 'Animation must change pixels')
await page.getByRole('button', { name: 'Pause animation', exact: true }).click()
await page.getByRole('button', { name: 'side', exact: true }).click()
await page.waitForTimeout(350)
assert(!paused.equals(await page.locator('canvas').screenshot()), 'Side view must change the camera')
await page.getByRole('button', { name: 'Reset camera', exact: true }).click()
await page.getByRole('button', { name: 'Expand viewer', exact: true }).click()
assert(await page.locator('.focus-view').count() === 1)
await page.getByRole('button', { name: 'Exit focused view', exact: true }).click()
await page.getByRole('button', { name: 'Forest A moment in the wild.', exact: true }).click()
await page.waitForTimeout(700)
await page.screenshot({ path: `${output}/forest.png`, fullPage: true })
const downloadWait = page.waitForEvent('download')
await page.getByRole('button', { name: 'Save studio image', exact: true }).click()
await (await downloadWait).saveAs(`${output}/capture.png`)
await page.getByRole('button', { name: 'Save Charizard', exact: true }).click()
await page.reload()
await ready(page)
assert(await page.getByRole('button', { name: 'Remove Charizard from collection', exact: true }).count() === 1)
await page.getByRole('button', { name: 'Collection 1', exact: true }).click()
assert(await page.locator('.pokemon-card').count() === 1)
await page.getByRole('button', { name: 'View Charizard', exact: true }).click()
await ready(page)
await page.getByRole('button', { name: 'Explore', exact: true }).click()
await page.getByRole('searchbox').fill('ピカチュウ')
assert(await page.locator('.pokemon-card').count() === 1)
await page.getByRole('button', { name: 'View Pikachu', exact: true }).click()
await ready(page)
assert(await page.locator('h1').innerText() === 'Pikachu.')
await page.evaluate(() => { location.hash = 'pokemon=25&scene=night' })
await page.waitForTimeout(150)
await ready(page)
assert(await page.locator('.viewer-stage.night').count() === 1)
await page.getByText('Skip to viewer', { exact: true }).focus()
await page.keyboard.press('Enter')
assert(await page.locator('h1').innerText() === 'Pikachu.')
assert((await page.evaluate(() => location.hash)).includes('pokemon=25'))
await page.getByRole('button', { name: 'Studio', exact: true }).click()
await page.getByRole('button', { name: 'Explore the geometry', exact: true }).click()
assert(await page.getByRole('button', { name: 'Explore the geometry', exact: true }).getAttribute('aria-pressed') === 'true')
await page.getByLabel('Render quality', { exact: true }).selectOption('standard')
await page.getByRole('button', { name: 'Reset studio', exact: true }).click()
await page.getByLabel('Generation', { exact: true }).selectOption('8')
await page.getByRole('searchbox').fill('899')
await page.getByRole('button', { name: 'View Wyrdeer', exact: true }).click()
await ready(page)
assert((await page.locator('.specimen-heading .eyebrow').innerText()).toLowerCase().includes('generation viii'))
await page.getByLabel('Type', { exact: true }).selectOption('fire')
assert(await page.getByText('No Pokémon found.', { exact: true }).count() === 1)
await page.getByLabel('Generation', { exact: true }).selectOption('0')
await page.getByLabel('Type', { exact: true }).selectOption('')
await page.getByRole('searchbox').fill('1025')
await page.getByRole('button', { name: 'View Pecharunt', exact: true }).click()
await ready(page)
assert(await page.locator('h1').innerText() === 'Pecharunt.')
await page.getByRole('button', { name: 'About Atlas & credits', exact: true }).click()
assert(await page.locator('dialog').evaluate(dialog => dialog.open))
await page.keyboard.press('Escape')
assert(!await page.locator('dialog').evaluate(dialog => dialog.open))
await page.getByRole('searchbox').fill('does not exist')
assert(await page.getByText('No Pokémon found.', { exact: true }).count() === 1)

const mobileContext = await browser.newContext({ locale: 'en-US', viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true })
const mobile = await mobileContext.newPage()
mobile.on('pageerror', error => errors.push(error.message))
await mobile.goto(base)
await ready(mobile)
await noOverflow(mobile)
await mobile.screenshot({ path: `${output}/mobile.png`, fullPage: true })
await mobile.getByRole('button', { name: 'Browse 1,025 Pokémon', exact: true }).click()
await mobile.getByRole('searchbox').fill('850')
await mobile.getByRole('button', { name: 'View Sizzlipede', exact: true }).click()
await ready(mobile)
assert(await mobile.locator('h1').innerText() === 'Sizzlipede.')
await mobile.screenshot({ path: `${output}/mobile-sizzlipede.png`, fullPage: true })
await mobile.setViewportSize({ width: 320, height: 568 })
await noOverflow(mobile)
await mobile.screenshot({ path: `${output}/mobile-320.png`, fullPage: true })
await mobileContext.close()

const reducedContext = await browser.newContext({ locale: 'en-US', viewport: { width: 1000, height: 800 }, reducedMotion: 'reduce' })
const reduced = await reducedContext.newPage()
reduced.on('pageerror', error => errors.push(error.message))
await reduced.goto(base)
await ready(reduced)
assert(await reduced.getByRole('button', { name: 'Play animation', exact: true }).count() === 1)
await reduced.waitForTimeout(500)
const still = await reduced.locator('canvas').screenshot()
await reduced.waitForTimeout(350)
assert(still.equals(await reduced.locator('canvas').screenshot()), 'Reduced motion starts with a still model')
await reducedContext.close()

let offlineVerified = false
if (process.env.ATLAS_VERIFY_PWA === '1') {
  await page.goto(`${base}/#pokemon=6&scene=studio`)
  await ready(page)
  await page.waitForFunction(async () => (await navigator.serviceWorker.getRegistrations()).some(r => !!r.active), null, { timeout: 45000 })
  await page.waitForFunction(() => !!navigator.serviceWorker.controller, null, { timeout: 30_000 })
  const manifest = await page.evaluate(async () => {
    const link = document.querySelector('link[rel=manifest]')
    return (await fetch(link.href)).json()
  })
  assert.equal(manifest.display, 'standalone')
  assert.equal(manifest.icons.length, 3)
  await context.setOffline(true)
  await page.reload()
  await ready(page)
  const cdp = await context.newCDPSession(page)
  await cdp.send('Network.overrideNetworkState', { offline: true, latency: 0, downloadThroughput: -1, uploadThroughput: -1 })
  await page.getByText('You’re offline.', { exact: false }).waitFor()
  await page.screenshot({ path: `${output}/offline.png`, fullPage: true })
  offlineVerified = true
  await context.setOffline(false)
}
assert.deepEqual(errors, [], 'No unhandled browser exceptions')
const result = { base, desktop: true, mobile390: true, mobile320: true, pause: true, animation: true, angles: true, capture: true, favoritesPersisted: true, japaneseSearch: true, lastSpecies: true, sameSelection: true, homeModel: true, generationFilter: true, typeFilter: true, reducedMotion: true, offlineVerified, errors }
await writeFile(`${output}/verification.json`, JSON.stringify(result, null, 2))
console.log(JSON.stringify(result, null, 2))
} finally { await browser.close() }
