import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { chromium, expect, appBase } from './helpers.mjs'
const output=process.env.ATLAS_QA_DIR || 'work/scene-sharing/browser'
await mkdir(output,{recursive:true})
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-webgpu','--enable-unsafe-swiftshader']})
const errors=[]
const source=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']})
const page=await source.newPage()
page.on('pageerror',e=>errors.push(e.message))
const ready=async p=>{await p.locator('.live-dot:not(.loading)').waitFor({timeout:120000});await p.locator('.loader').waitFor({state:'hidden'});assert.equal(await p.locator('.viewer-error').count(),0)}
const state=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('atlas-scenes-v1')))
const members=s=>s.draft.members.map(({key,...member})=>member)
const fixture={id:'fixture',name:'Private local name',members:[6,1,25,133,7,6].map((speciesId,i)=>({key:`fixture-${i}`,speciesId,...(i===0?{formId:'charizard-mega-x'}:{}),shiny:i===0,x:-3+i,z:i%2?1:-1,rotation:-90+i*30,scale:0.7+i*0.1})),settings:{playing:false,rotate:false,speed:1.25,light:1.2,habitat:'forest',wireframe:false,shiny:false,quality:'standard',animation:0},camera:{position:[8,7,13],target:[0,1,0]}}
try{
 await page.goto(`${appBase}/?lang=en#pokemon=1&scene=studio`);await ready(page)
 await page.getByRole('button',{name:'Together',exact:true}).click();await ready(page)
 await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({name:'scene.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,scene:fixture}))})
 await expect.poll(async()=>members(await state(page)).length).toBe(6);await ready(page)
 await page.getByRole('slider',{name:'Left / right',exact:true}).focus();await page.keyboard.press('End')
 await expect.poll(()=>new URL(page.url()).hash.includes('layout=')).toBe(true)
 await page.locator('.share-button').click()
 const link=await page.evaluate(()=>navigator.clipboard.readText())
 assert.equal(new URL(link).origin,new URL(appBase).origin)
 assert(new URL(link).hash.includes('layout='));assert(link.length<4096)
 const sent=await state(page)
 assert(members(sent).some(m=>m.x===4))
 const payload=JSON.parse(Buffer.from(new URLSearchParams(new URL(link).hash.slice(1)).get('layout'),'base64url').toString())
 assert(!JSON.stringify(payload).includes('Private local name'))
 assert(!JSON.stringify(payload).includes('fixture-'))
 const recipient=await browser.newContext({viewport:{width:390,height:844}})
 assert.deepEqual((await recipient.storageState()).origins,[])
 const other=await recipient.newPage();other.on('pageerror',e=>errors.push(e.message))
 await other.goto(link);await ready(other)
 const received=await state(other)
 assert.deepEqual(members(received),members(sent))
 assert.deepEqual(received.draft.settings,sent.draft.settings)
 for(const key of ['position','target'])for(let i=0;i<3;i++)assert(Math.abs(received.draft.camera[key][i]-payload.c[key][i])<0.001)
 assert.equal(await other.getByRole('button',{name:'Together',exact:true}).getAttribute('aria-pressed'),'true')
 assert(await other.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))
 await other.screenshot({path:`${output}/received-mobile.png`,fullPage:true})
 await other.reload();await ready(other);assert.deepEqual(members(await state(other)),members(sent))
 await other.getByRole('button',{name:'Save scene',exact:true}).click()
 const saved=(await state(other)).saved
 await page.getByRole('slider',{name:'Left / right',exact:true}).focus();await page.keyboard.press('Home')
 await page.locator('.share-button').click();const second=await page.evaluate(()=>navigator.clipboard.readText())
 await other.evaluate(url=>{location.hash=new URL(url).hash},second);await ready(other)
 await expect.poll(async()=>JSON.stringify(members(await state(other)))).toBe(JSON.stringify(members(await state(page))))
 assert.deepEqual((await state(other)).saved,saved)
 const before=await state(other)
 await other.evaluate(()=>{const hash=new URLSearchParams(location.hash.slice(1));hash.set('layout','invalid');location.hash=hash.toString()})
 await other.getByText('Preview unavailable',{exact:true}).waitFor()
 assert.deepEqual(await state(other),before)
 await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{configurable:true,value:()=>Promise.reject(new Error('denied'))}))
 await page.locator('.share-button').click()
 await page.getByText('Copy the address from your browser to share this Pokémon.',{exact:true}).waitFor()
 assert(new URLSearchParams(new URL(page.url()).hash.slice(1)).get('layout'))
 assert.deepEqual(errors,[])
 await writeFile(`${output}/results.json`,JSON.stringify({linkLength:link.length,sixMembers:true,formsAndShiny:true,placement:true,camera:true,settings:true,freshContext:true,reload:true,hashChange:true,savedScenesPreserved:true,malformedLinkPreservesState:true,clipboardDeniedFallback:true,mobile390:true,errors},null,2))
 console.log('Six-member scene URL restored in a clean context; edits, camera, reload, malformed links and clipboard fallback passed.')
 await recipient.close()
}finally{await source.close();await browser.close()}
