name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Run Biome check
        run: bun run lint

      - name: Build project
        run: bun run build

      - name: Check build output
        run: |
          ls -la out/ 2>/dev/null || echo "out/ directory not found"
          ls -la .next/ || echo ".next/ directory not found"
